#----------------------------------
# Makefile for EMU-LATER emulator project
# Tested under:
#
# author: Matthew Smith mrs9107@g.rit.edu
#----------------------------------

## for GCC
CC = gcc
CFLAGS = Wall -c99 
DFLAGS = -g

#build whole project
emu-later: main.c
    $(CC) $(CFLAGS) $(DFLAGS)  -o emu-later main.c cpu.o ppu.o

cpu.o:  cpu.c cpu.h
    $(CC) $(CFLAGS) $(DFLAGS) -c cpu.c

ppu.o: ppu.c ppu.h
    $(CC) $(CFLAGS) $(DFLAGS) -c ppu.c




