#----------------------------------
# Makefile for EMU-LATER emulator project
# Tested under:
#
# author: Matthew Smith mrs9107@g.rit.edu
#----------------------------------

## for GCC
CC = gcc
CFLAGS = Wall -c99 
DFLAGS = -g

#build whole project
emu-later: core.c
    $(CC) $(CFLAGS) $(DFLAGS) -o emu-later core.c core.h cpu.o 

cpu.o:  cpu.c cpu.h common.h
    $(CC) $(CFLAGS) $(DFLAGS) -c cpu.c

rom.o: rom.c rom.h common.h
    $(CC) $(CFLAGS) $(DFLAGS) -c rom.c
